### ISSUE TITLE
Adding a custom class to the trix-editor via className prop is not possible

### ISSUE THREAD

**Issue by alejo4373** [abhaynikam/react-trix-rte#30]
I need the ability to pass a custom class name to `<trix-editor>` because I want to override a css property that is set via the default [`trix.css`](https://github.com/basecamp/trix/blob/main/dist/trix.css#L11). More specifically I want to override `min-height` because I want the editor to have different heights at different times.

It looks like we could accomplish this through [`trixEditorOptions`](https://github.com/abhaynikam/react-trix-rte/blob/b8f0be29db72749aecccb0f7a046cf1ce950a732/src/components/ReactTrixRTEInput/ReactTrixRTEInput.jsx#L87). 

I'm open to collaborating on this further.

**Comment by abhaynikam** [comment]
@alejo4373 Sounds good to me. Please feel free to raise a PR. 😊

**Comment by alejo4373** [comment]
What do you think of updating storybook? It took me some time to figure how to implement the new story with the older API. [See the change in API here](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#hoisted-csf-annotations) for how to add `parameters` and `decorators`.

**Comment by abhaynikam** [comment]
We can log a separate issue for upgrading Storybook. Closing this issue as PR is merged.
